[project]
name = "lanauthgate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi==0.104.1",
    "jinja2==3.1.2",
    "python-multipart==0.0.6",
    "uvicorn[standard]==0.24.0",
]
